version: "3.6"
services:
  jupyter-8888:
    image: "tensorflow/tensorflow:latest-gpu-jupyter"
    environment:
      - JUPYTER_TOKEN=${ADMIN_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: [gpu]
    ports:
      - 172.17.0.1:7654:8888
    volumes:
      - ./workspace:/workspace
      - ./data:/data
      - ./notebooks:/tf/notebooks
